# Resize plugin configuration

# Language: English: en, Русский: ru, Español: es, Português - Brazil: pt_br, Deutsch: de, Polski: pl
lang: en

# Delay for the /resize command (prevents spamming)
cooldown: 5
# Plugin prefix
prefix: "&e&l[&aResize&e&l]&r "

# Whether to save the player's size after reconnecting
save-sizes: true

# Maximum and minimum size
scale:
  min: 0.6
  max: 1.6

# Animation adds smoothness when changing size
animation:
  enabled: true
  duration: 1

# Settings for resetting player size when taking or dealing damage
reset-on-damage:
  player:
    # If the player dealt damage to another player
    deal: true
    # If the player received damage from another player
    receive: true
    # If the player dies
    death: true

  mob:
    # If the player dealt damage to a mob
    deal: true
    # If the player received damage from a mob
    receive: true

  other:
    # If the player dealt damage to "other"
    deal: true
    # If the player received damage from "other"
    receive: true
# Should resets apply to admins with resize.admin permission
admin-reset: false

worlds:
  # blacklist / whitelist
  mode: blacklist
  # for example: world_nether, world_the_end
  list:
    - spawn
    - lobby